content = inspec.profile.file('terraform.json')
params = JSON.parse(content)

ACCESS_KEY = params['access_key']['value']
APPLICATION_NAME = params['application_name']['value']

title "Terraform Module Integration Test"

control "control-1.0" do
  impact 1.0
  title "Verify AWS IAM user"
  description "Testing to see whether Vault Approle was able to execute the IAM role bound to the Vault-AWS Secrets Role"
  describe aws_iam_user(user_name: APPLICATION_NAME) do
    it { should exist }
    its('access_keys') { should be_empty }
  end
end

control "control-2.0" do
  impact 1.0
  title "Verify Invalid AWS IAM user"
  description "Test that an IAM user does not exist"
  describe aws_iam_user(user_name: 'invalid-user') do
    it { should_not exist }
  end
end

control "control-3.0" do
  impact 1.0
  title "Verify AWS IAM user access_keys"
  description "Testing integrity of AWS IAM user access key generated by Vault"
  describe aws_iam_access_key(access_key: ACCESS_KEY) do
    it { should exist }
    its('last_used_date') { should be > Time.now - 1 * 86400 }
  end
end
